nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Custom-Auth']
        expose_headers: ['Link']
        max_age: 3600
        hosts: []
    paths:
        '^/': null
